account/urls.py
from django.urls import path

from account import views

app_name = "account"
urlpatterns = [
    path("", views.login_view, name="login"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
]

api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"todos", views.TodoViewSet)

app_name = "api"
urlpatterns = [
    path("", include(router.urls)),
]

lists/urls.py
from django.urls import path

from lists import views

app_name = "lists"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.add_todo, name="add_todo"),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("account.urls")),
    path("todolist/", include("lists.urls")),
    path("api/", include("api.urls")),
]

todoapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>TO DO LIST</title>
  <meta name="description" content="TO DO LIST APP">

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
  {% load static %}

  <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.2/normalize.min.css">
  <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <link rel="stylesheet" type='text/css' href="{% static 'css/custom.css' %}">
  {% block css %}{% endblock %}

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'js/site.js' %}"></script>
  {% block js %}{% endblock %}

</head>

<body>

  <div class="container">
    <div class="navbar-spacer"></div>
    <nav class="navbar">
      <div class="container">
        <ul class="navbar-list">
          <li class="navbar-item"><a class="navbar-link" href="{% url 'lists:index' %}">TO DO LIST</a></li>
          {% if not user.is_authenticated %}
          <li class="navbar-item">
            <a class="navbar-link" href="{% url 'account:login' %}">Login</a> {% else %}
            <li class="navbar-item">
              <a class="navbar-link" href="#" data-popover="#moreNavPopover">{{ user.username }}</a>
              <div id="moreNavPopover" class="popover">
                <ul class="popover-list">
                  <li class="popover-item">
                    <a class="popover-link" href="{% url 'account:logout' %}">logout</a>
                  </li>
                </ul>
              </div>
            </li>
            {% endif %}
        </ul>
      </div>
    </nav>
    {% block body %}{% endblock %}
  </div>
</body>

</html>